package model;

import javax.persistence.*;

/**
 * Ingrediente generated by hbm2java
 */
@Entity
@Table(name="Ingrediente")
public class Ingrediente implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set recIngs = new HashSet(0);

	public Ingrediente() {
	}

	public Ingrediente(String nombre, Set recIngs) {
		this.nombre = nombre;
		this.recIngs = recIngs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getRecIngs() {
		return this.recIngs;
	}

	public void setRecIngs(Set recIngs) {
		this.recIngs = recIngs;
	}

}
