// default package
// Generated Dec 12, 2016 4:03:32 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Receta generated by hbm2java
 */
public class Receta implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String preparacion;
	private int tiempo;
	private Set recIngs = new HashSet(0);

	public Receta() {
	}

	public Receta(String nombre, String preparacion, int tiempo) {
		this.nombre = nombre;
		this.preparacion = preparacion;
		this.tiempo = tiempo;
	}

	public Receta(String nombre, String preparacion, int tiempo, Set recIngs) {
		this.nombre = nombre;
		this.preparacion = preparacion;
		this.tiempo = tiempo;
		this.recIngs = recIngs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPreparacion() {
		return this.preparacion;
	}

	public void setPreparacion(String preparacion) {
		this.preparacion = preparacion;
	}

	public int getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(int tiempo) {
		this.tiempo = tiempo;
	}

	public Set getRecIngs() {
		return this.recIngs;
	}

	public void setRecIngs(Set recIngs) {
		this.recIngs = recIngs;
	}

}
