// default package
// Generated Dec 12, 2016 4:03:32 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * RecIng generated by hbm2java
 */
public class RecIng implements java.io.Serializable {

	private Integer id;
	private Ingrediente ingrediente;
	private Receta receta;
	private float cantidad;
	private String unidadMedida;

	public RecIng() {
	}

	public RecIng(Ingrediente ingrediente, Receta receta, float cantidad, String unidadMedida) {
		this.ingrediente = ingrediente;
		this.receta = receta;
		this.cantidad = cantidad;
		this.unidadMedida = unidadMedida;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Ingrediente getIngrediente() {
		return this.ingrediente;
	}

	public void setIngrediente(Ingrediente ingrediente) {
		this.ingrediente = ingrediente;
	}

	public Receta getReceta() {
		return this.receta;
	}

	public void setReceta(Receta receta) {
		this.receta = receta;
	}

	public float getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(float cantidad) {
		this.cantidad = cantidad;
	}

	public String getUnidadMedida() {
		return this.unidadMedida;
	}

	public void setUnidadMedida(String unidadMedida) {
		this.unidadMedida = unidadMedida;
	}

}
